version: '2'
services:
  app1:
    build: ./app
    container_name: app1
    environment:
      - APP_NAME="app1"
      - APP_PORT=3001
    depends_on:
      - depscontainer
    volumes:
      - deps:/app/data
  app2:
    build: ./app
    container_name: app2
    environment:
      - APP_NAME="app2"
      - APP_PORT=3002
    depends_on:
      - depscontainer
    volumes:
      - deps:/app/data
  depscontainer:
    build: ./datacontainer
    container_name: depscontainer
    volumes:
      - deps:/app/data
volumes:
  deps:
    driver: local
